### ISSUE TITLE
E: Version '5.6.27-1debian8' for 'mysql-server' was not found

### ISSUE THREAD

**Issue by yangboz** [innossh/docker-fluentd-memcached#2]
---> Running in 24f29a237651
Get:1 http://repo.mysql.com jessie InRelease [21.7 kB]
Get:2 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:3 http://repo.mysql.com jessie/mysql-5.6 amd64 Packages [2755 B]
Get:4 http://httpredir.debian.org jessie-updates InRelease [142 kB]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [387 kB]
Get:6 http://httpredir.debian.org jessie Release.gpg [2373 B]
Get:7 http://httpredir.debian.org jessie Release [148 kB]
Get:8 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:9 http://httpredir.debian.org jessie/main amd64 Packages [9032 kB]
Fetched 9817 kB in 11s (838 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '5.6.27-1debian8' for 'mysql-server' was not found,

**Comment by innossh** [comment]
Fixed by #3
